Ротация баннеров
Fuchsoria/banners-rotation pull request #1
Opened 2021-07-25 17:13 UTC by Fuchsoria

2021-07-31 23:09 UTC, Fuchsoria commented
**Integration tests:**

Creating postgres_test ...
Creating rabbit_test   ...
Creating postgres_test ... done
Creating rabbit_test   ... done
Creating banners-rotation_test ...
Creating banners-rotation_test ... done
Creating banners-rotation-integration-tests_integration_tests_1 ...
Creating banners-rotation-integration-tests_integration_tests_1 ... done
Creating banners-rotation-integration-tests_integration_tests_run ...
Creating banners-rotation-integration-tests_integration_tests_run ... done
=== RUN   TestHTTP
=== RUN   TestHTTP/test_banner_create
=== RUN   TestHTTP/test_slot_create
=== RUN   TestHTTP/test_social-demo_create
=== RUN   TestHTTP/test_add_banner_to_rotation
=== RUN   TestHTTP/test_remove_banner_from_rotation
=== RUN   TestHTTP/test_add_banner_click
=== RUN   TestHTTP/test_get_banner
=== RUN   TestHTTP/test_get_banner_from_not_existed_slot
=== RUN   TestHTTP/test_remove_not_existed_banner_from_rotation
=== RUN   TestHTTP/test_empty_body_add_banner
=== RUN   TestHTTP/test_empty_body_remove_banner
=== RUN   TestHTTP/test_empty_body_add_click
=== RUN   TestHTTP/test_empty_body_get_banner
--- PASS: TestHTTP (0.04s)
    --- PASS: TestHTTP/test_banner_create (0.00s)
    --- PASS: TestHTTP/test_slot_create (0.00s)
    --- PASS: TestHTTP/test_social-demo_create (0.00s)
    --- PASS: TestHTTP/test_add_banner_to_rotation (0.00s)
    --- PASS: TestHTTP/test_remove_banner_from_rotation (0.01s)
    --- PASS: TestHTTP/test_add_banner_click (0.00s)
    --- PASS: TestHTTP/test_get_banner (0.00s)
    --- PASS: TestHTTP/test_get_banner_from_not_existed_slot (0.00s)
    --- PASS: TestHTTP/test_remove_not_existed_banner_from_rotation (0.00s)
    --- PASS: TestHTTP/test_empty_body_add_banner (0.00s)
    --- PASS: TestHTTP/test_empty_body_remove_banner (0.00s)
    --- PASS: TestHTTP/test_empty_body_add_click (0.00s)
    --- PASS: TestHTTP/test_empty_body_get_banner (0.00s)
PASS
ok      github.com/Fuchsoria/banners-rotation/tests     0.038s
Stopping banners-rotation_test ...
Stopping rabbit_test           ...
Stopping postgres_test         ...
Stopping banners-rotation_test ... done
Stopping postgres_test         ... done
Stopping rabbit_test           ... done
Removing banners-rotation-integration-tests_integration_tests_run_f101d1bfe1af ...
Removing banners-rotation-integration-tests_integration_tests_1                ...
Removing banners-rotation_test                                                 ...
Removing rabbit_test                                                           ...
Removing postgres_test                                                         ...
Removing banners-rotation_test                                                 ... done
Removing postgres_test                                                         ... done
Removing rabbit_test                                                           ... done
Removing banners-rotation-integration-tests_integration_tests_1                ... done
Removing banners-rotation-integration-tests_integration_tests_run_f101d1bfe1af ... done
Removing network banners-rotation-integration-tests_postgres_test
Removing network banners-rotation-integration-tests_rabbit_test
Removing network banners-rotation-integration-tests_banners-rotation_test

2021-08-01 08:56 UTC, farir1408 requested changes

2021-08-01 08:56 UTC, farir1408 commented on cmd/banners-rotation/Dockerfile
> +FROM golang:1.16 as build
Лучше расположить это в директории build

2021-08-01 08:56 UTC, farir1408 commented on cmd/banners-rotation/config.go
> +package main
Можно вынести в отдельный пакет в /internal

2021-08-01 08:56 UTC, farir1408 commented on internal/app/app.go
> +func (a *App) GetStorage() Storage {
А нужны ли эти геттеры? Или нам лучше скрыть детали за фасадом App ?

2021-08-01 08:56 UTC, farir1408 commented on Makefile
> +BIN := "./bin/banners-rotation"
А как накатываются миграции в базу? не хотим ли добавить сюда ещё один таргет на миграции

2021-08-01 08:56 UTC, farir1408 commented on internal/storage/sql/storage.go
> +		return err
Хороший тон - использование врапа ошибок. Тогда из названия будет понятно куда смотреть. Это быстрее чем смотреть по стек-трейсу.

2021-08-01 08:56 UTC, farir1408 commented on internal/storage/storage.go
> +package storage
Это можно поместить в тот же sqlstorage и использовать в качестве моделей. Так как у структур есть теги бд, то это должны быть внутренними структурами пакета.

2021-08-01 08:56 UTC, farir1408 commented on migrations/init_with_data.sql
> +CREATE TABLE "slots" (
Дата-миграцию лучше обозвать как-то типа фикстуры, и поместить в отдельной папке. Тогда не придётся дублировать код инициализации бд.

2021-08-01 08:56 UTC, farir1408 commented on proto/BannersRotation/BannersRotation.proto
> +syntax = "proto3";
Лучше это поместить в api/banner.proto, так как это спецификация нашего API

2021-08-01 08:58 UTC, farir1408 commented
Здравствуйте!

Хорошая работа, есть пара небольших замечаний. Ещё хотелось бы видеть юнит-тесты на внутренние пакеты, например для бандита, + было бы круто написать интеграционный тест на сторедж.

2021-08-01 10:40 UTC, Fuchsoria commented on Makefile
> +BIN := "./bin/banners-rotation"
Через docker-compose файлы при создании базы инициализируются файлы

2021-08-01 10:44 UTC, Fuchsoria commented
> Здравствуйте!
> 
> Хорошая работа, есть пара небольших замечаний. Ещё хотелось бы видеть юнит-тесты на внутренние пакеты, например для бандита, + было бы круто написать интеграционный тест на сторедж. 

Бандит же и так сейчас полностью покрыт юнит тестами? По поводу сторейджа он в принципе покрыт тестами не на прямую, а за счёт интеграционных тестов http, так как проверяется результат в базе данных. В принципе продублирую интеграционники для прямого теста сторейджа

2021-08-01 11:55 UTC, Fuchsoria commented on migrations/init_with_data.sql
> +CREATE TABLE "slots" (
Назвал так по причине того что миграция происходит через докер, через volume
`    volumes:
      - ./migrations/init_with_data.sql:/docker-entrypoint-initdb.d/init.sql`

2021-08-01 12:03 UTC, Fuchsoria commented on internal/storage/storage.go
> +package storage
Убрал пакет storage, перенёс структуры в sqlstorage

2021-08-01 12:03 UTC, Fuchsoria commented on internal/app/app.go
> +func (a *App) GetStorage() Storage {
Депрекейтед код, использовался ранее пока не было app прослойки, удалил

2021-08-01 12:03 UTC, Fuchsoria commented on cmd/banners-rotation/config.go
> +package main
Вынес

2021-08-01 12:03 UTC, Fuchsoria commented on cmd/banners-rotation/Dockerfile
> +FROM golang:1.16 as build
Переместил

2021-08-01 17:33 UTC, Fuchsoria commented on internal/storage/sql/storage.go
> +		return err
Заврапил ошибки

2021-08-01 17:43 UTC, farir1408 commented on Makefile
> +BIN := "./bin/banners-rotation"
Лучше сделать через отдельный инструмент. Так как если поднимать инфраструктуру не из докера-компоуза, 
 через тотже кубернетес. И отдельно запускать бд, то миграции не накатятся. Но в целом в данной работе это не обязательно, а только рекомендация.

2021-08-01 17:43 UTC, farir1408 commented on migrations/init_with_data.sql
> +CREATE TABLE "slots" (
ну, лучше наверное не привязываться к докер-компоузу, но это тоже не критично.

2021-08-01 17:46 UTC, farir1408 commented
По бандиту - увидел. По интеграционным тестам - на api - это круто, но тест на апи должен быть без привязки к бд, и если мы завтра сменим sqlstorage на какой-нибудь файл, тесты api всё равно должны работать, так как они тестируют api, а не то, что в кишках. А вот интеграционный тест на конкретный сторедж как раз и тестирует, что там внутри всё ок, и всё сохраняется.

2021-08-01 17:53 UTC, Fuchsoria commented
> По бандиту - увидел. По интеграционным тестам - на api - это круто, но тест на апи должен быть без привязки к бд, и если мы завтра сменим sqlstorage на какой-нибудь файл, тесты api всё равно должны работать, так как они тестируют api, а не то, что в кишках. А вот интеграционный тест на конкретный сторедж как раз и тестирует, что там внутри всё ок, и всё сохраняется.

Получается лучше их просто разделить и http интеграционные проверять только респонс?

2021-08-02 16:43 UTC, Fuchsoria commented on proto/BannersRotation/BannersRotation.proto
> +syntax = "proto3";
Переместил

2021-08-02 16:59 UTC, Fuchsoria commented
@farir1408 разделил интеграционные тесты на тесты сторейджа и запросов к api, обновил комментарий с результатами из интеграционных тестов https://github.com/Fuchsoria/banners-rotation/pull/1#issuecomment-890414952

2021-08-11 12:02 UTC, farir1408 approved these changes

2021-08-11 12:02 UTC, farir1408 commented on cmd/banners-rotation/main.go
> +	storage, err := sqlstorage.New(ctx, configuration.DB.ConnectionString, producer)
Не очень хорошо, что у нас сторедж отвечает и за конект к бд, и за продьюсинг. Возможно стоит. вынести продюсер на уровень выше, либо это уже не сторедж, а какой-то более умный фасад.

2021-08-11 12:02 UTC, farir1408 commented on internal/amqp/producer/producer.go
> +			"",     // exchange
Можно добавить в функцию опциональные аргументы для более точной настройки отправки сообщения (по желанию)

2021-08-11 12:02 UTC, farir1408 commented on internal/storage/sql/storage.go
> +	err = s.db.Select(&bannersInSlot, "SELECT * FROM banners_rotation WHERE slot_id=$1", slotID)
лучше явно перечислять список параметров, которые достаём из бд.

2021-08-11 12:02 UTC, farir1408 commented on proto/api/banner.proto
> +syntax = "proto3";
proto в пути лишнее. в первую очередь это api, а уже потом идёт детализация по формату.

2021-08-11 12:02 UTC, farir1408 commented on proto/google/api/annotations.proto
> +// Copyright 2015 Google LLC
подобные файлы лучше вынести куда-нибудь в third_party/*.proto чтобы они не засоряли api спецификацию.

2021-08-11 12:07 UTC, farir1408 commented
Здравствуйте!

Отличная работа, есть небольшие замечания, но они не являются критичными, поэтому дз принимаю.
15/15.

2021-08-11 12:53 UTC, Fuchsoria commented on proto/google/api/annotations.proto
> +// Copyright 2015 Google LLC
путь выбирал идентичный путю из оригинального репозитория https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto

2021-08-11 12:54 UTC, Fuchsoria commented on proto/google/api/annotations.proto
> +// Copyright 2015 Google LLC
как и в принципе держал все протобафы в одной папке

2021-08-11 12:57 UTC, Fuchsoria commented on internal/storage/sql/storage.go
> +	err = s.db.Select(&bannersInSlot, "SELECT * FROM banners_rotation WHERE slot_id=$1", slotID)
как я понимаю сейчас .Select метод вытягивает и записывает слайс по фиксированной структуре и думаю он выдаст ошибку если что-то не так с параметрами?

2021-08-14 13:12 UTC, Fuchsoria commented on proto/google/api/annotations.proto
> +// Copyright 2015 Google LLC
Изменил

2021-08-14 13:12 UTC, Fuchsoria commented on proto/api/banner.proto
> +syntax = "proto3";
Убрал

2021-08-14 13:12 UTC, Fuchsoria commented on cmd/banners-rotation/main.go
> +	storage, err := sqlstorage.New(ctx, configuration.DB.ConnectionString, producer)
Вынес его в app

2021-08-14 13:13 UTC, merged